export type ProductStatus = 'active' | 'draft' | 'archived'

export interface AdminProduct {
  id: string
  name: string
  slug: string
  sku: string
  category: string
  price: number
  comparePrice: number | null
  stock: number
  status: ProductStatus
  featured: boolean
  bestSeller: boolean
  imageUrl: string
  shortDescription: string
  createdAt: string
  // Extra fields
  material?: string
  diameter?: string
  weight?: string
  color?: string
  colorHex?: string
  printTemp?: string
  bedTemp?: string
  buildVolume?: string
  printSpeed?: string
  nozzleDiameter?: string
  supportedMaterials?: string
  connectivity?: string
  warranty?: string
  fileFormat?: string[]
  licenseType?: string
  polyCount?: string
  isDigitalDownload?: boolean
  resinType?: string
  bottleSize?: string
  compatiblePrinters?: string
  exposureTime?: string
}

export const adminProducts: AdminProduct[] = [
  {
    id: '1',
    name: 'Bambu Lab X1 Carbon',
    slug: 'bambu-lab-x1-carbon',
    sku: 'PRNT-001',
    category: 'printers',
    price: 1299.00,
    comparePrice: 1499.00,
    stock: 8,
    status: 'active',
    featured: true,
    bestSeller: true,
    imageUrl: 'https://picsum.photos/seed/printer1/200/200',
    shortDescription: 'Imprimante 3D multicolore haute vitesse avec calibration automatique.',
    createdAt: '2024-01-15T10:00:00Z',
    buildVolume: '256 x 256 x 256 mm',
    printSpeed: '500 mm/s',
    nozzleDiameter: '0.4 mm',
    supportedMaterials: 'PLA, PETG, TPU, ABS, ASA',
    connectivity: 'Wi-Fi, LAN',
    warranty: '1 an',
  },
  {
    id: '2',
    name: 'Creality Ender-3 V3 SE',
    slug: 'creality-ender-3-v3-se',
    sku: 'PRNT-002',
    category: 'printers',
    price: 189.00,
    comparePrice: 229.00,
    stock: 22,
    status: 'active',
    featured: false,
    bestSeller: true,
    imageUrl: 'https://picsum.photos/seed/printer2/200/200',
    shortDescription: 'Imprimante 3D FDM d\'entrée de gamme avec mise à niveau automatique.',
    createdAt: '2024-01-20T10:00:00Z',
    buildVolume: '220 x 220 x 250 mm',
    printSpeed: '250 mm/s',
    nozzleDiameter: '0.4 mm',
    supportedMaterials: 'PLA, PETG, TPU',
    connectivity: 'USB, microSD',
    warranty: '1 an',
  },
  {
    id: '3',
    name: 'Prusa MK4',
    slug: 'prusa-mk4',
    sku: 'PRNT-003',
    category: 'printers',
    price: 799.00,
    comparePrice: null,
    stock: 5,
    status: 'active',
    featured: true,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/printer3/200/200',
    shortDescription: 'Imprimante 3D open-source fiable avec détection de filament.',
    createdAt: '2024-02-01T10:00:00Z',
    buildVolume: '250 x 210 x 220 mm',
    printSpeed: '200 mm/s',
    nozzleDiameter: '0.4 mm',
    supportedMaterials: 'PLA, PETG, ABS, ASA, Flex',
    connectivity: 'USB, Ethernet',
    warranty: '2 ans',
  },
  {
    id: '4',
    name: 'Filament PLA+ Rouge Carmin 1kg',
    slug: 'filament-pla-plus-rouge-carmin-1kg',
    sku: 'FIL-001',
    category: 'filament',
    price: 24.90,
    comparePrice: 29.90,
    stock: 45,
    status: 'active',
    featured: false,
    bestSeller: true,
    imageUrl: 'https://picsum.photos/seed/filament1/200/200',
    shortDescription: 'Filament PLA+ rouge carmin haute qualité, idéal pour les prototypes.',
    createdAt: '2024-01-10T10:00:00Z',
    material: 'PLA+',
    diameter: '1.75 mm',
    weight: '1 kg',
    color: 'Rouge Carmin',
    colorHex: '#DC143C',
    printTemp: '200-220°C',
    bedTemp: '55-65°C',
  },
  {
    id: '5',
    name: 'Filament PETG Transparent 1kg',
    slug: 'filament-petg-transparent-1kg',
    sku: 'FIL-002',
    category: 'filament',
    price: 27.90,
    comparePrice: null,
    stock: 30,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/filament2/200/200',
    shortDescription: 'Filament PETG transparent résistant aux UV et à l\'humidité.',
    createdAt: '2024-01-12T10:00:00Z',
    material: 'PETG',
    diameter: '1.75 mm',
    weight: '1 kg',
    color: 'Transparent',
    colorHex: '#E8F4F8',
    printTemp: '230-250°C',
    bedTemp: '70-80°C',
  },
  {
    id: '6',
    name: 'Filament ABS Noir Intense 1kg',
    slug: 'filament-abs-noir-intense-1kg',
    sku: 'FIL-003',
    category: 'filament',
    price: 22.90,
    comparePrice: 26.90,
    stock: 3,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/filament3/200/200',
    shortDescription: 'Filament ABS noir résistant à la chaleur, idéal pour pièces techniques.',
    createdAt: '2024-01-18T10:00:00Z',
    material: 'ABS',
    diameter: '1.75 mm',
    weight: '1 kg',
    color: 'Noir',
    colorHex: '#1a1a1a',
    printTemp: '230-240°C',
    bedTemp: '100-110°C',
  },
  {
    id: '7',
    name: 'Résine Standard Grise 1L',
    slug: 'resine-standard-grise-1l',
    sku: 'RES-001',
    category: 'resin',
    price: 34.90,
    comparePrice: 39.90,
    stock: 18,
    status: 'active',
    featured: false,
    bestSeller: true,
    imageUrl: 'https://picsum.photos/seed/resin1/200/200',
    shortDescription: 'Résine photopolymère standard grise pour imprimantes MSLA/DLP.',
    createdAt: '2024-01-25T10:00:00Z',
    resinType: 'Standard',
    bottleSize: '1 L',
    color: 'Gris',
    compatiblePrinters: 'Elegoo Saturn, Anycubic Photon',
    exposureTime: '2-3 secondes',
  },
  {
    id: '8',
    name: 'Résine ABS-Like Transparente 500ml',
    slug: 'resine-abs-like-transparente-500ml',
    sku: 'RES-002',
    category: 'resin',
    price: 22.90,
    comparePrice: null,
    stock: 12,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/resin2/200/200',
    shortDescription: 'Résine ABS-Like transparente très résistante aux chocs.',
    createdAt: '2024-02-05T10:00:00Z',
    resinType: 'ABS-Like',
    bottleSize: '500 ml',
    color: 'Transparent',
    compatiblePrinters: 'Tous imprimantes MSLA 405nm',
    exposureTime: '3-4 secondes',
  },
  {
    id: '9',
    name: 'Modèle 3D - Dragon Médiéval',
    slug: 'modele-3d-dragon-medieval',
    sku: 'MOD-001',
    category: 'models',
    price: 9.90,
    comparePrice: null,
    stock: 999,
    status: 'active',
    featured: true,
    bestSeller: true,
    imageUrl: 'https://picsum.photos/seed/model1/200/200',
    shortDescription: 'Modèle 3D haute résolution d\'un dragon médiéval avec détails fins.',
    createdAt: '2024-01-08T10:00:00Z',
    fileFormat: ['STL', 'OBJ', '3MF'],
    licenseType: 'Personnel',
    polyCount: '2.5M polygones',
    isDigitalDownload: true,
  },
  {
    id: '10',
    name: 'Modèle 3D - Buste Napoléon',
    slug: 'modele-3d-buste-napoleon',
    sku: 'MOD-002',
    category: 'models',
    price: 14.90,
    comparePrice: null,
    stock: 999,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/model2/200/200',
    shortDescription: 'Buste historique de Napoléon Bonaparte, haute fidélité.',
    createdAt: '2024-01-22T10:00:00Z',
    fileFormat: ['STL', '3MF'],
    licenseType: 'Commercial',
    polyCount: '1.8M polygones',
    isDigitalDownload: true,
  },
  {
    id: '11',
    name: 'Modèle 3D - Architecture Gothique',
    slug: 'modele-3d-architecture-gothique',
    sku: 'MOD-003',
    category: 'models',
    price: 19.90,
    comparePrice: 24.90,
    stock: 999,
    status: 'active',
    featured: true,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/model3/200/200',
    shortDescription: 'Collection d\'éléments architecturaux gothiques pour maquettes.',
    createdAt: '2024-02-10T10:00:00Z',
    fileFormat: ['STL', 'OBJ'],
    licenseType: 'Personnel',
    polyCount: '3.2M polygones',
    isDigitalDownload: true,
  },
  {
    id: '12',
    name: 'Kit Outils Impression 3D Pro',
    slug: 'kit-outils-impression-3d-pro',
    sku: 'TOOL-001',
    category: 'tools',
    price: 49.90,
    comparePrice: 59.90,
    stock: 15,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/tool1/200/200',
    shortDescription: 'Kit complet d\'outils pour post-traitement et maintenance d\'imprimante 3D.',
    createdAt: '2024-01-30T10:00:00Z',
  },
  {
    id: '13',
    name: 'Spatule Acier Inoxydable',
    slug: 'spatule-acier-inoxydable',
    sku: 'TOOL-002',
    category: 'tools',
    price: 12.90,
    comparePrice: null,
    stock: 0,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/tool2/200/200',
    shortDescription: 'Spatule professionnelle pour décoller facilement vos impressions.',
    createdAt: '2024-02-12T10:00:00Z',
  },
  {
    id: '14',
    name: 'Plateau Magnétique Flexible',
    slug: 'plateau-magnetique-flexible',
    sku: 'ACC-001',
    category: 'accessories',
    price: 29.90,
    comparePrice: 34.90,
    stock: 20,
    status: 'active',
    featured: false,
    bestSeller: true,
    imageUrl: 'https://picsum.photos/seed/acc1/200/200',
    shortDescription: 'Plateau d\'impression magnétique flexible 235x235mm universel.',
    createdAt: '2024-01-14T10:00:00Z',
  },
  {
    id: '15',
    name: 'Buse Laiton 0.4mm Pack x5',
    slug: 'buse-laiton-0-4mm-pack-x5',
    sku: 'SPARE-001',
    category: 'spare-parts',
    price: 8.90,
    comparePrice: null,
    stock: 7,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/spare1/200/200',
    shortDescription: 'Pack de 5 buses laiton 0.4mm compatibles Ender 3, CR-10.',
    createdAt: '2024-01-28T10:00:00Z',
  },
  {
    id: '16',
    name: 'Filament TPU Flexible Blanc 500g',
    slug: 'filament-tpu-flexible-blanc-500g',
    sku: 'FIL-004',
    category: 'filament',
    price: 19.90,
    comparePrice: 23.90,
    stock: 25,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/filament4/200/200',
    shortDescription: 'Filament TPU flexible blanc pour pièces élastiques et souples.',
    createdAt: '2024-02-03T10:00:00Z',
    material: 'TPU',
    diameter: '1.75 mm',
    weight: '500 g',
    color: 'Blanc',
    colorHex: '#FFFFFF',
    printTemp: '220-240°C',
    bedTemp: '25-60°C',
  },
  {
    id: '17',
    name: 'Résine 8K Dentaire Beige 500ml',
    slug: 'resine-8k-dentaire-beige-500ml',
    sku: 'RES-003',
    category: 'resin',
    price: 54.90,
    comparePrice: 64.90,
    stock: 6,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/resin3/200/200',
    shortDescription: 'Résine 8K ultra-précise pour applications dentaires et bijouterie.',
    createdAt: '2024-02-08T10:00:00Z',
    resinType: 'Dentaire 8K',
    bottleSize: '500 ml',
    color: 'Beige',
    compatiblePrinters: 'Phrozen Sonic Mighty 8K, Elegoo Saturn 3',
    exposureTime: '1.5-2 secondes',
  },
  {
    id: '18',
    name: 'Modèle 3D - Figurine Anime Pack',
    slug: 'modele-3d-figurine-anime-pack',
    sku: 'MOD-004',
    category: 'models',
    price: 29.90,
    comparePrice: 39.90,
    stock: 999,
    status: 'active',
    featured: false,
    bestSeller: true,
    imageUrl: 'https://picsum.photos/seed/model4/200/200',
    shortDescription: 'Pack de 10 figurines anime prêtes à imprimer, haute résolution.',
    createdAt: '2024-02-15T10:00:00Z',
    fileFormat: ['STL'],
    licenseType: 'Personnel',
    polyCount: '1.2M polygones',
    isDigitalDownload: true,
  },
  {
    id: '19',
    name: 'Nettoyant Isopropanol 99% 1L',
    slug: 'nettoyant-isopropanol-99-1l',
    sku: 'TOOL-003',
    category: 'tools',
    price: 14.90,
    comparePrice: null,
    stock: 0,
    status: 'active',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/tool3/200/200',
    shortDescription: 'Alcool isopropylique 99% pour nettoyage des pièces en résine.',
    createdAt: '2024-01-05T10:00:00Z',
  },
  {
    id: '20',
    name: 'Câble PTFE Haute Température 1m',
    slug: 'cable-ptfe-haute-temperature-1m',
    sku: 'SPARE-002',
    category: 'spare-parts',
    price: 6.90,
    comparePrice: null,
    stock: 35,
    status: 'draft',
    featured: false,
    bestSeller: false,
    imageUrl: 'https://picsum.photos/seed/spare2/200/200',
    shortDescription: 'Tube PTFE ID 2mm, OD 4mm, résistant jusqu\'à 260°C, longueur 1m.',
    createdAt: '2024-02-18T10:00:00Z',
  },
]
